name: Anka
description: Runs your build steps in Anka virtual machines
author: https://github.com/chef
requirements:
  - anka
configuration:
  properties:
    vm-name:
      type: string
    vm-registry-tag:
      type: string
    vm-registry-version:
      type: integer
    always-pull:
      type: string
    inherit-environment-vars:
      type: boolean
    environment-file:
      type: string
    no-volume:
      type: boolean
    volume:
      type: string
    wait-network:
      type: boolean
    wait-time:
      type: boolean
    workdir:
      type: string
    workdir-create:
      type: boolean
    debug:
      type: boolean
    anka-debug:
      type: boolean
    cleanup:
      type: boolean
    bash-interactive:
      type: boolean
    pre-commands:
      type: array
    post-commands:
      type: array
    failover-registries:
      type: array
    pre-execute-sleep:
      type: integer
    pre-execute-ping-sleep:
      type: string
    modify-cpu:
      type: integer
    modify-ram:
      type: integer
    modify-mac:
      type: string
    start-devices:
      type: array
  required:
    - vm-name
additionalProperties: false
